/**
 * ReportFooter
 *
 * Footer component for PDF/HTML reports
 */

import React from 'react';

interface ReportFooterProps {
  showDisclaimer?: boolean;
  disclaimerText?: string;
  showBranding?: boolean;
  pageNumber?: number;
  totalPages?: number;
  generatedAt?: string;
}

export const ReportFooter: React.FC<ReportFooterProps> = ({
  showDisclaimer = true,
  disclaimerText,
  showBranding = true,
  pageNumber,
  totalPages,
  generatedAt
}) => {
  const defaultDisclaimer =
    "This report was generated automatically based on data analysis. " +
    "Recommendations should be reviewed by qualified professionals before implementation.";

  return (
    <footer className="mt-12 pt-6 border-t border-gray-200 print:mt-8 print:pt-4">
      {showDisclaimer && (
        <div className="mb-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
          <p className="text-xs text-gray-600 leading-relaxed">
            <span className="font-medium">Disclaimer: </span>
            {disclaimerText || defaultDisclaimer}
          </p>
        </div>
      )}

      <div className="flex items-center justify-between text-xs text-gray-500">
        <div className="flex items-center gap-2">
          {showBranding && (
            <>
              <svg className="w-4 h-4 text-blue-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
              <span>Generated by <span className="font-medium text-gray-700">Holistic SEO Tool</span></span>
            </>
          )}
        </div>

        <div className="flex items-center gap-4">
          {generatedAt && (
            <span>{generatedAt}</span>
          )}
          {pageNumber !== undefined && totalPages !== undefined && (
            <span>Page {pageNumber} of {totalPages}</span>
          )}
        </div>
      </div>
    </footer>
  );
};

/**
 * Section divider component for reports
 */
export const ReportSectionDivider: React.FC<{
  title?: string;
  className?: string;
}> = ({ title, className = '' }) => {
  if (title) {
    return (
      <div className={`flex items-center gap-4 my-8 ${className}`}>
        <div className="flex-1 h-px bg-gray-200" />
        <span className="text-sm font-medium text-gray-500 uppercase tracking-wider">
          {title}
        </span>
        <div className="flex-1 h-px bg-gray-200" />
      </div>
    );
  }

  return <hr className={`my-8 border-gray-200 ${className}`} />;
};

/**
 * Page break hint for PDF generation
 */
export const PageBreak: React.FC = () => (
  <div className="page-break-before print:break-before-page" style={{ pageBreakBefore: 'always' }} />
);

export default ReportFooter;
